Webview bridge interface 개발, 테스트 ui 추가
flarelane/FlareLane-iOS-SDK pull request #23
Opened 2024-01-31 03:06 UTC by jpyo0613

### web app 을 위한 webview javascript bridge 등록 개발
- 브릿지 함수 : setUserId, setTags, trackEvent (web sdk) 에서 호출됨
- [연동 가이드](https://www.notion.so/flarelane/522cb10d0d504607a400d0deb3b84ccd?v=0eeda4a18c4640d9a4145b2118bb1d04&p=3ab6ac6e47b34416bf00fd9efe7dff08&pm=s)

### 테스트 ui 추가
- 웹뷰 테스트는 프로젝트 내부 example/webview_bridge_test.html 파일을 웹뷰에 띄우고 브릿지와 연동되는 구조임

https://github.com/flarelane/FlareLane-iOS-SDK/assets/33045561/271ed202-e221-4ce6-b647-7e2589f5390e

2024-01-31 06:54 UTC, junyeongCHOI commented on FlareLane/Classes/FlareLaneJavascriptInterface.swift
> +    }
data가 nil인 경우에도 trackEvent가 불려야 할 것 같아요

2024-01-31 10:30 UTC, minhyeok4dev requested changes

2024-01-31 10:30 UTC, minhyeok4dev commented on FlareLane/Classes/FlareLaneJavascriptInterface.swift
> +        Logger.verbose("setUserId() userId=\(userId ?? "nil")")
Delete duplicated logs

2024-01-31 10:30 UTC, minhyeok4dev commented on FlareLane/Classes/FlareLaneJavascriptInterface.swift
> +        let userId = body["userId"] as? String
How to separate the userId is null or exists?

2024-01-31 10:30 UTC, minhyeok4dev commented on Example/FlareLane/Info.plist
> +	<true/>
Set **false** to test along with other platforms like Firebase.

2024-02-01 05:45 UTC, jpyo0613 commented on Example/FlareLane/Info.plist
> +	<true/>
Applied successfully

2024-02-01 05:46 UTC, jpyo0613 commented on FlareLane/Classes/FlareLaneJavascriptInterface.swift
> +        let userId = body["userId"] as? String
Added fallback logic for cases where the userId key is missing

2024-02-02 02:54 UTC, minhyeok4dev approved these changes

2024-02-05 01:18 UTC, merged